name: First Workflow
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: display secret
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo $SECRETS_CONTEXT
      - name: Print Goodbye
        run: echo "Done - Bye!"
